version: "3"

services:
  app:
    container_name: train-ocr-heb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: sh start.sh
